name: suryaichat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  phosphor_flutter: ^2.1.0
  speech_to_text: ^6.6.1
  http: ^1.2.1
  flutter_highlight: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/